# Generated by Django 4.2.13 on 2024-06-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('studentsId', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=240)),
                ('lastName', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=560)),
                ('createdAt', models.DateField()),
            ],
        ),
    ]
