# Generated by Django 4.2.13 on 2024-06-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='studentsId',
            new_name='studentId',
        ),
    ]
